version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Preparing to build...
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3 bucket...
      - aws s3 sync build/ s3://ecommerce-platform-interview --delete

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
